### PR TITLE
fix 0005 sbml model; rerun 0007 with log10 llh corrected

### LINKED ISSUE #11: challenge for 0007
Hi,

for test model 0007, I get the correct chi2 value, but the likelihood differs. 

As you can see in this R code snippet:
> chi2 <- obj(pouter)$value
> chi2
[1] 3.226562
> -0.5*(chi2+sum(log(2*pi*c(0.5,0.6,0.7)^2)))
[1] -2.809449

dMod obtains -2.8 instead of -1.38 as in the given solution.

All other test cases obtain the correct results for both chi2 and llh. Presumably it has something to do with the different log-transformations. Could it be that you internally rescale the noise parameter for log10 or log. But I think this is wrong.

Best,
Marcus

### PR DESCRIPTION
**Pull request by yannikschaelte**
also fixes #11

### CODE REVIEW

**Comment by yannikschaelte** [comment]
background on 0005: the condition-specific parameter `offset_A` is not strictly required by all tools as they can automatically add it,but it is required by petab standard, so we explicitly add it to the sbml model.

**Comment by yannikschaelte** [comment]
Upon `petabtests_create` without the modified sbml, there is
```
Condition table contains column for unknown entity 'offset_A'. Column names must match parameter, species or compartment IDs specified in the SBML model.
Missing parameter(s) in parameter table: {'offset_A'}
Not OK
```
adding the parameter to the sbml does not change the value though, so that seems fine ...

**Comment by yannikschaelte** [comment]
adding it for now to the model, and let's maybe have observable parameters not introduced in the sbml as an additional test case.

**Comment by dweindl** [comment]
Okay, good to test the two features separately.

**Pull request merged**
